In [2]:
import numpy as np
import random

# Define the environment (4x4 grid)
n_states = 16  # states: 0 to 15
actions = [0, 1, 2, 3]  # up, right, down, left

# Rewards dataset: -1 for each move, 0 for goal
rewards = np.full(n_states, -1)
goal_state = 15
rewards[goal_state] = 100

# Define possible transitions (walls at edges)
def next_state(state, action):
    row, col = divmod(state, 4)
    if action == 0 and row > 0:
        row -= 1  # up
    elif action == 1 and col < 3:
        col += 1  # right
    elif action == 2 and row < 3:
        row += 1  # down
    elif action == 3 and col > 0:
        col -= 1  # left
    return row * 4 + col


# Initialize Q-table
Q = np.zeros((n_states, len(actions)))

# Hyperparameters
alpha = 0.7  # learning rate
gamma = 0.95  # discount factor
epsilon = 0.1  # exploration probability
episodes = 500

# Q-Learning algorithm
for episode in range(episodes):
    state = random.randint(0, n_states - 1)

    while state != goal_state:
        # ε-greedy action selection
        if random.uniform(0, 1) < epsilon:
            action = random.choice(actions)
        else:
            action = np.argmax(Q[state, :])

        new_state = next_state(state, action)
        reward = rewards[new_state]

        # Update Q-value
        Q[state, action] = Q[state, action] + alpha * (
            reward + gamma * np.max(Q[new_state, :]) - Q[state, action]
        )

        state = new_state

# Show final Q-table
print("Q-Table:")
print(np.round(Q, 2))

# Extract optimal policy
optimal_policy = np.argmax(Q, axis=1)
action_map = ['↑', '→', '↓', '←']

print("\nOptimal Policy:")
for i in range(n_states):
    print(f"State {i}: {action_map[optimal_policy[i]]}")

# Demonstrate a path from start (state 0)
state = 0
path = [state]
while state != goal_state:
    action = optimal_policy[state]
    state = next_state(state, action)
    path.append(state)

print("\nOptimal Path from State 0 to Goal:")
print(" -> ".join(map(str, path)))

Q-Table:
[[ -2.22  -2.22  72.85  -2.66]
 [ 66.06  77.74  70.56  -2.59]
 [ 77.1   72.8   82.88  70.71]
 [ 50.39  -1.58  61.34  77.74]
 [ 68.04  77.74  53.71  72.24]
 [ 66.11  82.88  57.59  49.79]
 [ 77.74  88.3   88.28  77.73]
 [ 72.85  85.88  94.    82.88]
 [ -2.12  82.88  -2.05  68.33]
 [ 75.6   88.3   80.27  54.  ]
 [ 82.88  94.    65.59  82.88]
 [ 88.3   93.99 100.    88.29]
 [ 47.31  88.3   -1.38  -1.38]
 [ 57.75  94.    80.28  82.21]
 [ 85.9  100.    93.77  80.35]
 [  0.     0.     0.     0.  ]]

Optimal Policy:
State 0: ↓
State 1: →
State 2: ↓
State 3: ←
State 4: →
State 5: →
State 6: →
State 7: ↓
State 8: →
State 9: →
State 10: →
State 11: ↓
State 12: →
State 13: →
State 14: →
State 15: ↑

Optimal Path from State 0 to Goal:
0 -> 4 -> 5 -> 6 -> 7 -> 11 -> 15
